tanuki-frontend:
  type: nodejs:20
  # disk: 1024
  # mounts:
  #   '/.cache': { source: local, source_path: "tanuki-frontend/cache" }
  #   '/.config': { source: local, source_path: "tanuki-frontend/config" }
  web:
    locations:
      "/app":
        root: "build"
        passthru: true
        index:
          - "index.html"
        scripts: true
        allow: true
        headers:
          Access-Control-Allow-Origin: "*"
  hooks:
    build: npm install && npm run build
  source:
    root: tanuki-frontend

# tanuki-promo:
#   type: nodejs:20
#   mounts:
#     '/.cache': { source: local, source_path: "tanuki-promo/cache" }
#     '/.config': { source: local, source_path: "tanuki-promo/config" }
#   web:
#     locations:
#       "/":
#         root: "build"
#         passthru: true
#         index:
#           - "index.html"
#         scripts: true
#         allow: true
#         headers:
#           Access-Control-Allow-Origin: "*"
#   hooks:
#     build: npm install && npm run build
#   source:
#     root: tanuki-promo

tanuki-backend:
  type: "rust:1"
  relationships:
    postgresdatabase: "dbpostgres:postgresql"
    rediscache: "cacheredis:redis"
  hooks:
    build: cargo build --release
  web:
    commands:
      start: ./target/release/tanuki
  source:
    root: "tanuki-backend"