# tanuki-frontend
"https://{default}/app":
  type: upstream
  upstream: "tanuki-frontend:http"
  id: "tanuki-frontend"

"http://{default}/app":
  type: redirect
  to: "https://{default}/app"

"https://{default}":
  type: redirect
  to: "https://{default}/app"

"http://{default}":
  type: redirect
  to: "https://{default}/app"

# tanuki-promo
# "https://{default}/":
#   type: upstream
#   upstream: "tanuki-frontend:http"
#   id: "tanuki-frontend"

# "http://{default}/":
#   type: redirect
#   to: "https://{default}"

# API
"https://{default}/api":
  type: upstream
  upstream: "tanuki-backend:http"
  id: "tanuki-backend"

"http://{default}/api":
  type: redirect
  to: "https://{default}/api"