# The name given to the PostgreSQL service (lowercase alphanumeric only).
dbpostgres:
  type: postgresql:15
  disk: 256

# The name given to the Redis service (lowercase alphanumeric only).
cacheredis:
  type: redis:7.2
